services:
  python-app:
    build: .
    container_name: windalertserver
    restart: always
    tty: true
    environment:
      - CHAT_ID=${CHAT_ID}
      - BOT_TOKEN=${BOT_TOKEN}
      - API_KEY=${API_KEY}